config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaria
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beneficiarium.rb
class Beneficiarium < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beneficiaria_controller.rb
class BeneficiariaController < ApplicationController
  before_action :set_beneficiarium, only: [:show, :edit, :update, :destroy]

  # GET /beneficiaria
  # GET /beneficiaria.json
  def index
    @beneficiaria = Beneficiarium.all
  end

  # GET /beneficiaria/1
  # GET /beneficiaria/1.json
  def show
  end

  # GET /beneficiaria/new
  def new
    @beneficiarium = Beneficiarium.new
  end

  # GET /beneficiaria/1/edit
  def edit
  end

  # POST /beneficiaria
  # POST /beneficiaria.json
  def create
    @beneficiarium = Beneficiarium.new(beneficiarium_params)

    respond_to do |format|
      if @beneficiarium.save
        format.html { redirect_to @beneficiarium, notice: 'Beneficiarium was successfully created.' }
        format.json { render :show, status: :created, location: @beneficiarium }
      else
        format.html { render :new }
        format.json { render json: @beneficiarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiaria/1
  # PATCH/PUT /beneficiaria/1.json
  def update
    respond_to do |format|
      if @beneficiarium.update(beneficiarium_params)
        format.html { redirect_to @beneficiarium, notice: 'Beneficiarium was successfully updated.' }
        format.json { render :show, status: :ok, location: @beneficiarium }
      else
        format.html { render :edit }
        format.json { render json: @beneficiarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beneficiaria/1
  # DELETE /beneficiaria/1.json
  def destroy
    @beneficiarium.destroy
    respond_to do |format|
      format.html { redirect_to beneficiaria_url, notice: 'Beneficiarium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiarium
      @beneficiarium = Beneficiarium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beneficiarium_params
      params.require(:beneficiarium).permit(:nombre, :estatura, :complexion, :tez)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beneficiaria_helper.rb
module BeneficiariaHelper
end

app/views/beneficiaria/_form.html.erb
<%= form_with(model: beneficiarium, local: true) do |form| %>
  <% if beneficiarium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beneficiarium.errors.count, "error") %> prohibited this beneficiarium from being saved:</h2>

      <ul>
      <% beneficiarium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :beneficiarium_nombre %>
  </div>

  <div class="field">
    <%= form.label :estatura %>
    <%= form.text_field :estatura, id: :beneficiarium_estatura %>
  </div>

  <div class="field">
    <%= form.label :complexion %>
    <%= form.text_field :complexion, id: :beneficiarium_complexion %>
  </div>

  <div class="field">
    <%= form.label :tez %>
    <%= form.text_field :tez, id: :beneficiarium_tez %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beneficiaria/edit.html.erb
<h1>Editing Beneficiarium</h1>

<%= render 'form', beneficiarium: @beneficiarium %>

<%= link_to 'Show', @beneficiarium %> |
<%= link_to 'Back', beneficiaria_path %>

app/views/beneficiaria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beneficiaria</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estatura</th>
      <th>Complexion</th>
      <th>Tez</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beneficiaria.each do |beneficiarium| %>
      <tr>
        <td><%= beneficiarium.nombre %></td>
        <td><%= beneficiarium.estatura %></td>
        <td><%= beneficiarium.complexion %></td>
        <td><%= beneficiarium.tez %></td>
        <td><%= link_to 'Show', beneficiarium %></td>
        <td><%= link_to 'Edit', edit_beneficiarium_path(beneficiarium) %></td>
        <td><%= link_to 'Destroy', beneficiarium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beneficiarium', new_beneficiarium_path %>

app/views/beneficiaria/new.html.erb
<h1>New Beneficiarium</h1>

<%= render 'form', beneficiarium: @beneficiarium %>

<%= link_to 'Back', beneficiaria_path %>

app/views/beneficiaria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @beneficiarium.nombre %>
</p>

<p>
  <strong>Estatura:</strong>
  <%= @beneficiarium.estatura %>
</p>

<p>
  <strong>Complexion:</strong>
  <%= @beneficiarium.complexion %>
</p>

<p>
  <strong>Tez:</strong>
  <%= @beneficiarium.tez %>
</p>

<%= link_to 'Edit', edit_beneficiarium_path(@beneficiarium) %> |
<%= link_to 'Back', beneficiaria_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apoyos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>